package com.fawkes.cpd.bim.common.model;

import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;
import java.sql.Timestamp;

public class Issue extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.target_id
     *
     * @mbggenerated
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.assigend_users
     *
     * @mbggenerated
     */
    private String assigendUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.due_date
     *
     * @mbggenerated
     */
    private Timestamp dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.flow_id
     *
     * @mbggenerated
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.marker_point
     *
     * @mbggenerated
     */
    private String markerPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue.create_user_full_name
     *
     * @mbggenerated
     */
    private String createUserFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cpd_issue
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.target_id
     *
     * @return the value of cpd_issue.target_id
     *
     * @mbggenerated
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.target_id
     *
     * @param targetId the value for cpd_issue.target_id
     *
     * @mbggenerated
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId == null ? null : targetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.title
     *
     * @return the value of cpd_issue.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.title
     *
     * @param title the value for cpd_issue.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.description
     *
     * @return the value of cpd_issue.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.description
     *
     * @param description the value for cpd_issue.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.status
     *
     * @return the value of cpd_issue.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.status
     *
     * @param status the value for cpd_issue.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.assigend_users
     *
     * @return the value of cpd_issue.assigend_users
     *
     * @mbggenerated
     */
    public String getAssigendUsers() {
        return assigendUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.assigend_users
     *
     * @param assigendUsers the value for cpd_issue.assigend_users
     *
     * @mbggenerated
     */
    public void setAssigendUsers(String assigendUsers) {
        this.assigendUsers = assigendUsers == null ? null : assigendUsers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.tags
     *
     * @return the value of cpd_issue.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.tags
     *
     * @param tags the value for cpd_issue.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.due_date
     *
     * @return the value of cpd_issue.due_date
     *
     * @mbggenerated
     */
    public Timestamp getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.due_date
     *
     * @param dueDate the value for cpd_issue.due_date
     *
     * @mbggenerated
     */
    public void setDueDate(Timestamp dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.flow_id
     *
     * @return the value of cpd_issue.flow_id
     *
     * @mbggenerated
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.flow_id
     *
     * @param flowId the value for cpd_issue.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.marker_point
     *
     * @return the value of cpd_issue.marker_point
     *
     * @mbggenerated
     */
    public String getMarkerPoint() {
        return markerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.marker_point
     *
     * @param markerPoint the value for cpd_issue.marker_point
     *
     * @mbggenerated
     */
    public void setMarkerPoint(String markerPoint) {
        this.markerPoint = markerPoint == null ? null : markerPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue.create_user_full_name
     *
     * @return the value of cpd_issue.create_user_full_name
     *
     * @mbggenerated
     */
    public String getCreateUserFullName() {
        return createUserFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue.create_user_full_name
     *
     * @param createUserFullName the value for cpd_issue.create_user_full_name
     *
     * @mbggenerated
     */
    public void setCreateUserFullName(String createUserFullName) {
        this.createUserFullName = createUserFullName == null ? null : createUserFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Issue other = (Issue) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getTargetId() == null ? other.getTargetId() == null : this.getTargetId().equals(other.getTargetId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAssigendUsers() == null ? other.getAssigendUsers() == null : this.getAssigendUsers().equals(other.getAssigendUsers()))
            && (this.getTags() == null ? other.getTags() == null : this.getTags().equals(other.getTags()))
            && (this.getDueDate() == null ? other.getDueDate() == null : this.getDueDate().equals(other.getDueDate()))
            && (this.getFlowId() == null ? other.getFlowId() == null : this.getFlowId().equals(other.getFlowId()))
            && (this.getMarkerPoint() == null ? other.getMarkerPoint() == null : this.getMarkerPoint().equals(other.getMarkerPoint()))
            && (this.getCreateUserFullName() == null ? other.getCreateUserFullName() == null : this.getCreateUserFullName().equals(other.getCreateUserFullName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getTargetId() == null) ? 0 : getTargetId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAssigendUsers() == null) ? 0 : getAssigendUsers().hashCode());
        result = prime * result + ((getTags() == null) ? 0 : getTags().hashCode());
        result = prime * result + ((getDueDate() == null) ? 0 : getDueDate().hashCode());
        result = prime * result + ((getFlowId() == null) ? 0 : getFlowId().hashCode());
        result = prime * result + ((getMarkerPoint() == null) ? 0 : getMarkerPoint().hashCode());
        result = prime * result + ((getCreateUserFullName() == null) ? 0 : getCreateUserFullName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", targetId=").append(targetId);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append(", assigendUsers=").append(assigendUsers);
        sb.append(", tags=").append(tags);
        sb.append(", dueDate=").append(dueDate);
        sb.append(", flowId=").append(flowId);
        sb.append(", markerPoint=").append(markerPoint);
        sb.append(", createUserFullName=").append(createUserFullName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}