package com.fawkes.cpd.bim.common.model;

import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;

public class IssueChangeRecord extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_change_record.issue_id
     *
     * @mbggenerated
     */
    private Long issueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_change_record.change_type
     *
     * @mbggenerated
     */
    private String changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_change_record.before_change_content
     *
     * @mbggenerated
     */
    private String beforeChangeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_change_record.after_change_content
     *
     * @mbggenerated
     */
    private String afterChangeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cpd_issue_change_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_change_record.issue_id
     *
     * @return the value of cpd_issue_change_record.issue_id
     *
     * @mbggenerated
     */
    public Long getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_change_record.issue_id
     *
     * @param issueId the value for cpd_issue_change_record.issue_id
     *
     * @mbggenerated
     */
    public void setIssueId(Long issueId) {
        this.issueId = issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_change_record.change_type
     *
     * @return the value of cpd_issue_change_record.change_type
     *
     * @mbggenerated
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_change_record.change_type
     *
     * @param changeType the value for cpd_issue_change_record.change_type
     *
     * @mbggenerated
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType == null ? null : changeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_change_record.before_change_content
     *
     * @return the value of cpd_issue_change_record.before_change_content
     *
     * @mbggenerated
     */
    public String getBeforeChangeContent() {
        return beforeChangeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_change_record.before_change_content
     *
     * @param beforeChangeContent the value for cpd_issue_change_record.before_change_content
     *
     * @mbggenerated
     */
    public void setBeforeChangeContent(String beforeChangeContent) {
        this.beforeChangeContent = beforeChangeContent == null ? null : beforeChangeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_change_record.after_change_content
     *
     * @return the value of cpd_issue_change_record.after_change_content
     *
     * @mbggenerated
     */
    public String getAfterChangeContent() {
        return afterChangeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_change_record.after_change_content
     *
     * @param afterChangeContent the value for cpd_issue_change_record.after_change_content
     *
     * @mbggenerated
     */
    public void setAfterChangeContent(String afterChangeContent) {
        this.afterChangeContent = afterChangeContent == null ? null : afterChangeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_change_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IssueChangeRecord other = (IssueChangeRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getIssueId() == null ? other.getIssueId() == null : this.getIssueId().equals(other.getIssueId()))
            && (this.getChangeType() == null ? other.getChangeType() == null : this.getChangeType().equals(other.getChangeType()))
            && (this.getBeforeChangeContent() == null ? other.getBeforeChangeContent() == null : this.getBeforeChangeContent().equals(other.getBeforeChangeContent()))
            && (this.getAfterChangeContent() == null ? other.getAfterChangeContent() == null : this.getAfterChangeContent().equals(other.getAfterChangeContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_change_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
        result = prime * result + ((getChangeType() == null) ? 0 : getChangeType().hashCode());
        result = prime * result + ((getBeforeChangeContent() == null) ? 0 : getBeforeChangeContent().hashCode());
        result = prime * result + ((getAfterChangeContent() == null) ? 0 : getAfterChangeContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_change_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", issueId=").append(issueId);
        sb.append(", changeType=").append(changeType);
        sb.append(", beforeChangeContent=").append(beforeChangeContent);
        sb.append(", afterChangeContent=").append(afterChangeContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}