package com.fawkes.cpd.bim.common.model;

import com.fawkes.core.base.model.BaseEntity;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class IssueReference extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_reference.issue_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("附件所属issue的唯一键Id")
    private Long issueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_reference.file_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("附件文件的名称")
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_reference.size
     *
     * @mbggenerated
     */
    @ApiModelProperty("附件文件的大小 单位字节")
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_reference.ext_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("附件文件类型(后缀名)")
    private String extName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpd_issue_reference.file_token
     *
     * @mbggenerated
     */
    @ApiModelProperty("附件文件的token")
    private String fileToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cpd_issue_reference
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_reference.issue_id
     *
     * @return the value of cpd_issue_reference.issue_id
     *
     * @mbggenerated
     */
    public Long getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_reference.issue_id
     *
     * @param issueId the value for cpd_issue_reference.issue_id
     *
     * @mbggenerated
     */
    public void setIssueId(Long issueId) {
        this.issueId = issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_reference.file_name
     *
     * @return the value of cpd_issue_reference.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_reference.file_name
     *
     * @param fileName the value for cpd_issue_reference.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_reference.size
     *
     * @return the value of cpd_issue_reference.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_reference.size
     *
     * @param size the value for cpd_issue_reference.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_reference.ext_name
     *
     * @return the value of cpd_issue_reference.ext_name
     *
     * @mbggenerated
     */
    public String getExtName() {
        return extName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_reference.ext_name
     *
     * @param extName the value for cpd_issue_reference.ext_name
     *
     * @mbggenerated
     */
    public void setExtName(String extName) {
        this.extName = extName == null ? null : extName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpd_issue_reference.file_token
     *
     * @return the value of cpd_issue_reference.file_token
     *
     * @mbggenerated
     */
    public String getFileToken() {
        return fileToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpd_issue_reference.file_token
     *
     * @param fileToken the value for cpd_issue_reference.file_token
     *
     * @mbggenerated
     */
    public void setFileToken(String fileToken) {
        this.fileToken = fileToken == null ? null : fileToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_reference
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IssueReference other = (IssueReference) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getIssueId() == null ? other.getIssueId() == null : this.getIssueId().equals(other.getIssueId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getExtName() == null ? other.getExtName() == null : this.getExtName().equals(other.getExtName()))
            && (this.getFileToken() == null ? other.getFileToken() == null : this.getFileToken().equals(other.getFileToken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_reference
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getExtName() == null) ? 0 : getExtName().hashCode());
        result = prime * result + ((getFileToken() == null) ? 0 : getFileToken().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpd_issue_reference
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", issueId=").append(issueId);
        sb.append(", fileName=").append(fileName);
        sb.append(", size=").append(size);
        sb.append(", extName=").append(extName);
        sb.append(", fileToken=").append(fileToken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}