package com.fawkes.sys.user.common.model;

import com.fawkes.core.base.model.BaseEntity;

import java.io.Serializable;

public class SysUserSchedule extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.lon
     *
     * @mbggenerated
     */
    private String lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.began_date
     *
     * @mbggenerated
     */
    private Long beganDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.end_date
     *
     * @mbggenerated
     */
    private Long endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.msg_type
     *
     * @mbggenerated
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.repeat_type
     *
     * @mbggenerated
     */
    private Integer repeatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.repeat_time
     *
     * @mbggenerated
     */
    private Long repeatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.repeat_status
     *
     * @mbggenerated
     */
    private Integer repeatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_schedule.tenant_id
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_schedule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.title
     *
     * @return the value of sys_user_schedule.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.title
     *
     * @param title the value for sys_user_schedule.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.lon
     *
     * @return the value of sys_user_schedule.lon
     *
     * @mbggenerated
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.lon
     *
     * @param lon the value for sys_user_schedule.lon
     *
     * @mbggenerated
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.lat
     *
     * @return the value of sys_user_schedule.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.lat
     *
     * @param lat the value for sys_user_schedule.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.began_date
     *
     * @return the value of sys_user_schedule.began_date
     *
     * @mbggenerated
     */
    public Long getBeganDate() {
        return beganDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.began_date
     *
     * @param beganDate the value for sys_user_schedule.began_date
     *
     * @mbggenerated
     */
    public void setBeganDate(Long beganDate) {
        this.beganDate = beganDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.end_date
     *
     * @return the value of sys_user_schedule.end_date
     *
     * @mbggenerated
     */
    public Long getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.end_date
     *
     * @param endDate the value for sys_user_schedule.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.msg_type
     *
     * @return the value of sys_user_schedule.msg_type
     *
     * @mbggenerated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.msg_type
     *
     * @param msgType the value for sys_user_schedule.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.repeat_type
     *
     * @return the value of sys_user_schedule.repeat_type
     *
     * @mbggenerated
     */
    public Integer getRepeatType() {
        return repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.repeat_type
     *
     * @param repeatType the value for sys_user_schedule.repeat_type
     *
     * @mbggenerated
     */
    public void setRepeatType(Integer repeatType) {
        this.repeatType = repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.repeat_time
     *
     * @return the value of sys_user_schedule.repeat_time
     *
     * @mbggenerated
     */
    public Long getRepeatTime() {
        return repeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.repeat_time
     *
     * @param repeatTime the value for sys_user_schedule.repeat_time
     *
     * @mbggenerated
     */
    public void setRepeatTime(Long repeatTime) {
        this.repeatTime = repeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.repeat_status
     *
     * @return the value of sys_user_schedule.repeat_status
     *
     * @mbggenerated
     */
    public Integer getRepeatStatus() {
        return repeatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.repeat_status
     *
     * @param repeatStatus the value for sys_user_schedule.repeat_status
     *
     * @mbggenerated
     */
    public void setRepeatStatus(Integer repeatStatus) {
        this.repeatStatus = repeatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_schedule.tenant_id
     *
     * @return the value of sys_user_schedule.tenant_id
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_schedule.tenant_id
     *
     * @param tenantId the value for sys_user_schedule.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_schedule
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUserSchedule other = (SysUserSchedule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getLon() == null ? other.getLon() == null : this.getLon().equals(other.getLon()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
            && (this.getBeganDate() == null ? other.getBeganDate() == null : this.getBeganDate().equals(other.getBeganDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getRepeatType() == null ? other.getRepeatType() == null : this.getRepeatType().equals(other.getRepeatType()))
            && (this.getRepeatTime() == null ? other.getRepeatTime() == null : this.getRepeatTime().equals(other.getRepeatTime()))
            && (this.getRepeatStatus() == null ? other.getRepeatStatus() == null : this.getRepeatStatus().equals(other.getRepeatStatus()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_schedule
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getLon() == null) ? 0 : getLon().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getBeganDate() == null) ? 0 : getBeganDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getRepeatType() == null) ? 0 : getRepeatType().hashCode());
        result = prime * result + ((getRepeatTime() == null) ? 0 : getRepeatTime().hashCode());
        result = prime * result + ((getRepeatStatus() == null) ? 0 : getRepeatStatus().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_schedule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", title=").append(title);
        sb.append(", lon=").append(lon);
        sb.append(", lat=").append(lat);
        sb.append(", beganDate=").append(beganDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", msgType=").append(msgType);
        sb.append(", repeatType=").append(repeatType);
        sb.append(", repeatTime=").append(repeatTime);
        sb.append(", repeatStatus=").append(repeatStatus);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}