package com.fawkes.sys.user.common.model;

import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class SysUser extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_no
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_fullname
     *
     * @mbggenerated
     */
    private String userFullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.tenant_id
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_status
     *
     * @mbggenerated
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_period
     *
     * @mbggenerated
     */
    private Integer accountPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_active_time
     *
     * @mbggenerated
     */
    private Date lastActiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.former_name
     *
     * @mbggenerated
     */
    private String formerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.citizenship
     *
     * @mbggenerated
     */
    private String citizenship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birth_day
     *
     * @mbggenerated
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.politics
     *
     * @mbggenerated
     */
    private String politics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.idcard_type
     *
     * @mbggenerated
     */
    private String idcardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.idcard_number
     *
     * @mbggenerated
     */
    private String idcardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.degree
     *
     * @mbggenerated
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.major_name
     *
     * @mbggenerated
     */
    private String majorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.stature
     *
     * @mbggenerated
     */
    private String stature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.native_place
     *
     * @mbggenerated
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.job_number
     *
     * @mbggenerated
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.marriage_state
     *
     * @mbggenerated
     */
    private String marriageState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.emergency_phone
     *
     * @mbggenerated
     */
    private String emergencyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.emergency_name
     *
     * @mbggenerated
     */
    private String emergencyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.office_location
     *
     * @mbggenerated
     */
    private String officeLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sign_token
     *
     * @mbggenerated
     */
    private String signToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.photo_token
     *
     * @mbggenerated
     */
    private String photoToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_init_pwd
     *
     * @mbggenerated
     */
    private Boolean isInitPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.office_phone
     *
     * @mbggenerated
     */
    private String officePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.other_phone
     *
     * @mbggenerated
     */
    private String otherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.working_seniority
     *
     * @mbggenerated
     */
    private String workingSeniority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.hiredate
     *
     * @mbggenerated
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_update_pwd_time
     *
     * @mbggenerated
     */
    private Timestamp lastUpdatePwdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.avatar_token
     *
     * @mbggenerated
     */
    private String avatarToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ext1
     *
     * @mbggenerated
     */
    private String ext1;


    private String newPost;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ext2
     *
     * @mbggenerated
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ext3
     *
     * @mbggenerated
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ext4
     *
     * @mbggenerated
     */
    private String ext4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ext5
     *
     * @mbggenerated
     */
    private String ext5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * 组token
     *
     */
    private String groupToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_no
     *
     * @return the value of sys_user.user_no
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_no
     *
     * @param userNo the value for sys_user.user_no
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_fullname
     *
     * @return the value of sys_user.user_fullname
     *
     * @mbggenerated
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_fullname
     *
     * @param userFullname the value for sys_user.user_fullname
     *
     * @mbggenerated
     */
    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname == null ? null : userFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_type
     *
     * @return the value of sys_user.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_type
     *
     * @param userType the value for sys_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.tenant_id
     *
     * @return the value of sys_user.tenant_id
     *
     * @mbggenerated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.tenant_id
     *
     * @param tenantId the value for sys_user.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_status
     *
     * @return the value of sys_user.account_status
     *
     * @mbggenerated
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_status
     *
     * @param accountStatus the value for sys_user.account_status
     *
     * @mbggenerated
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_period
     *
     * @return the value of sys_user.account_period
     *
     * @mbggenerated
     */
    public Integer getAccountPeriod() {
        return accountPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_period
     *
     * @param accountPeriod the value for sys_user.account_period
     *
     * @mbggenerated
     */
    public void setAccountPeriod(Integer accountPeriod) {
        this.accountPeriod = accountPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_active_time
     *
     * @return the value of sys_user.last_active_time
     *
     * @mbggenerated
     */
    public Date getLastActiveTime() {
        return lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_active_time
     *
     * @param lastActiveTime the value for sys_user.last_active_time
     *
     * @mbggenerated
     */
    public void setLastActiveTime(Date lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.former_name
     *
     * @return the value of sys_user.former_name
     *
     * @mbggenerated
     */
    public String getFormerName() {
        return formerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.former_name
     *
     * @param formerName the value for sys_user.former_name
     *
     * @mbggenerated
     */
    public void setFormerName(String formerName) {
        this.formerName = formerName == null ? null : formerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.citizenship
     *
     * @return the value of sys_user.citizenship
     *
     * @mbggenerated
     */
    public String getCitizenship() {
        return citizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.citizenship
     *
     * @param citizenship the value for sys_user.citizenship
     *
     * @mbggenerated
     */
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship == null ? null : citizenship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.age
     *
     * @return the value of sys_user.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.age
     *
     * @param age the value for sys_user.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birth_day
     *
     * @return the value of sys_user.birth_day
     *
     * @mbggenerated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birth_day
     *
     * @param birthDay the value for sys_user.birth_day
     *
     * @mbggenerated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.politics
     *
     * @return the value of sys_user.politics
     *
     * @mbggenerated
     */
    public String getPolitics() {
        return politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.politics
     *
     * @param politics the value for sys_user.politics
     *
     * @mbggenerated
     */
    public void setPolitics(String politics) {
        this.politics = politics == null ? null : politics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.idcard_type
     *
     * @return the value of sys_user.idcard_type
     *
     * @mbggenerated
     */
    public String getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.idcard_type
     *
     * @param idcardType the value for sys_user.idcard_type
     *
     * @mbggenerated
     */
    public void setIdcardType(String idcardType) {
        this.idcardType = idcardType == null ? null : idcardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.idcard_number
     *
     * @return the value of sys_user.idcard_number
     *
     * @mbggenerated
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.idcard_number
     *
     * @param idcardNumber the value for sys_user.idcard_number
     *
     * @mbggenerated
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.education
     *
     * @return the value of sys_user.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.education
     *
     * @param education the value for sys_user.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.degree
     *
     * @return the value of sys_user.degree
     *
     * @mbggenerated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.degree
     *
     * @param degree the value for sys_user.degree
     *
     * @mbggenerated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.major_name
     *
     * @return the value of sys_user.major_name
     *
     * @mbggenerated
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.major_name
     *
     * @param majorName the value for sys_user.major_name
     *
     * @mbggenerated
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.stature
     *
     * @return the value of sys_user.stature
     *
     * @mbggenerated
     */
    public String getStature() {
        return stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.stature
     *
     * @param stature the value for sys_user.stature
     *
     * @mbggenerated
     */
    public void setStature(String stature) {
        this.stature = stature == null ? null : stature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.weight
     *
     * @return the value of sys_user.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.weight
     *
     * @param weight the value for sys_user.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nation
     *
     * @return the value of sys_user.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nation
     *
     * @param nation the value for sys_user.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.native_place
     *
     * @return the value of sys_user.native_place
     *
     * @mbggenerated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.native_place
     *
     * @param nativePlace the value for sys_user.native_place
     *
     * @mbggenerated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nationality
     *
     * @return the value of sys_user.nationality
     *
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nationality
     *
     * @param nationality the value for sys_user.nationality
     *
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.job_number
     *
     * @return the value of sys_user.job_number
     *
     * @mbggenerated
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.job_number
     *
     * @param jobNumber the value for sys_user.job_number
     *
     * @mbggenerated
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber == null ? null : jobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.marriage_state
     *
     * @return the value of sys_user.marriage_state
     *
     * @mbggenerated
     */
    public String getMarriageState() {
        return marriageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.marriage_state
     *
     * @param marriageState the value for sys_user.marriage_state
     *
     * @mbggenerated
     */
    public void setMarriageState(String marriageState) {
        this.marriageState = marriageState == null ? null : marriageState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.emergency_phone
     *
     * @return the value of sys_user.emergency_phone
     *
     * @mbggenerated
     */
    public String getEmergencyPhone() {
        return emergencyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.emergency_phone
     *
     * @param emergencyPhone the value for sys_user.emergency_phone
     *
     * @mbggenerated
     */
    public void setEmergencyPhone(String emergencyPhone) {
        this.emergencyPhone = emergencyPhone == null ? null : emergencyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.emergency_name
     *
     * @return the value of sys_user.emergency_name
     *
     * @mbggenerated
     */
    public String getEmergencyName() {
        return emergencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.emergency_name
     *
     * @param emergencyName the value for sys_user.emergency_name
     *
     * @mbggenerated
     */
    public void setEmergencyName(String emergencyName) {
        this.emergencyName = emergencyName == null ? null : emergencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.office_location
     *
     * @return the value of sys_user.office_location
     *
     * @mbggenerated
     */
    public String getOfficeLocation() {
        return officeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.office_location
     *
     * @param officeLocation the value for sys_user.office_location
     *
     * @mbggenerated
     */
    public void setOfficeLocation(String officeLocation) {
        this.officeLocation = officeLocation == null ? null : officeLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sign_token
     *
     * @return the value of sys_user.sign_token
     *
     * @mbggenerated
     */
    public String getSignToken() {
        return signToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sign_token
     *
     * @param signToken the value for sys_user.sign_token
     *
     * @mbggenerated
     */
    public void setSignToken(String signToken) {
        this.signToken = signToken == null ? null : signToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.photo_token
     *
     * @return the value of sys_user.photo_token
     *
     * @mbggenerated
     */
    public String getPhotoToken() {
        return photoToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.photo_token
     *
     * @param photoToken the value for sys_user.photo_token
     *
     * @mbggenerated
     */
    public void setPhotoToken(String photoToken) {
        this.photoToken = photoToken == null ? null : photoToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_init_pwd
     *
     * @return the value of sys_user.is_init_pwd
     *
     * @mbggenerated
     */
    public Boolean getIsInitPwd() {
        return isInitPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_init_pwd
     *
     * @param isInitPwd the value for sys_user.is_init_pwd
     *
     * @mbggenerated
     */
    public void setIsInitPwd(Boolean isInitPwd) {
        this.isInitPwd = isInitPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.office_phone
     *
     * @return the value of sys_user.office_phone
     *
     * @mbggenerated
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.office_phone
     *
     * @param officePhone the value for sys_user.office_phone
     *
     * @mbggenerated
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.other_phone
     *
     * @return the value of sys_user.other_phone
     *
     * @mbggenerated
     */
    public String getOtherPhone() {
        return otherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.other_phone
     *
     * @param otherPhone the value for sys_user.other_phone
     *
     * @mbggenerated
     */
    public void setOtherPhone(String otherPhone) {
        this.otherPhone = otherPhone == null ? null : otherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.title
     *
     * @return the value of sys_user.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.title
     *
     * @param title the value for sys_user.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.working_seniority
     *
     * @return the value of sys_user.working_seniority
     *
     * @mbggenerated
     */
    public String getWorkingSeniority() {
        return workingSeniority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.working_seniority
     *
     * @param workingSeniority the value for sys_user.working_seniority
     *
     * @mbggenerated
     */
    public void setWorkingSeniority(String workingSeniority) {
        this.workingSeniority = workingSeniority == null ? null : workingSeniority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.hiredate
     *
     * @return the value of sys_user.hiredate
     *
     * @mbggenerated
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.hiredate
     *
     * @param hiredate the value for sys_user.hiredate
     *
     * @mbggenerated
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.remark
     *
     * @return the value of sys_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.remark
     *
     * @param remark the value for sys_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_update_pwd_time
     *
     * @return the value of sys_user.last_update_pwd_time
     *
     * @mbggenerated
     */
    public Timestamp getLastUpdatePwdTime() {
        return lastUpdatePwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_update_pwd_time
     *
     * @param lastUpdatePwdTime the value for sys_user.last_update_pwd_time
     *
     * @mbggenerated
     */
    public void setLastUpdatePwdTime(Timestamp lastUpdatePwdTime) {
        this.lastUpdatePwdTime = lastUpdatePwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.avatar_token
     *
     * @return the value of sys_user.avatar_token
     *
     * @mbggenerated
     */
    public String getAvatarToken() {
        return avatarToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.avatar_token
     *
     * @param avatarToken the value for sys_user.avatar_token
     *
     * @mbggenerated
     */
    public void setAvatarToken(String avatarToken) {
        this.avatarToken = avatarToken == null ? null : avatarToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nickname
     *
     * @return the value of sys_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nickname
     *
     * @param nickname the value for sys_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.introduction
     *
     * @return the value of sys_user.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.introduction
     *
     * @param introduction the value for sys_user.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sort
     *
     * @return the value of sys_user.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sort
     *
     * @param sort the value for sys_user.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ext1
     *
     * @return the value of sys_user.ext1
     *
     * @mbggenerated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ext1
     *
     * @param ext1 the value for sys_user.ext1
     *
     * @mbggenerated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ext2
     *
     * @return the value of sys_user.ext2
     *
     * @mbggenerated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ext2
     *
     * @param ext2 the value for sys_user.ext2
     *
     * @mbggenerated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ext3
     *
     * @return the value of sys_user.ext3
     *
     * @mbggenerated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ext3
     *
     * @param ext3 the value for sys_user.ext3
     *
     * @mbggenerated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ext4
     *
     * @return the value of sys_user.ext4
     *
     * @mbggenerated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ext4
     *
     * @param ext4 the value for sys_user.ext4
     *
     * @mbggenerated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ext5
     *
     * @return the value of sys_user.ext5
     *
     * @mbggenerated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ext5
     *
     * @param ext5 the value for sys_user.ext5
     *
     * @mbggenerated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUser other = (SysUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
                && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
                && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getUserNo() == null ? other.getUserNo() == null : this.getUserNo().equals(other.getUserNo()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getUserFullname() == null ? other.getUserFullname() == null : this.getUserFullname().equals(other.getUserFullname()))
                && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
                && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
                && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
                && (this.getAccountStatus() == null ? other.getAccountStatus() == null : this.getAccountStatus().equals(other.getAccountStatus()))
                && (this.getAccountPeriod() == null ? other.getAccountPeriod() == null : this.getAccountPeriod().equals(other.getAccountPeriod()))
                && (this.getLastActiveTime() == null ? other.getLastActiveTime() == null : this.getLastActiveTime().equals(other.getLastActiveTime()))
                && (this.getFormerName() == null ? other.getFormerName() == null : this.getFormerName().equals(other.getFormerName()))
                && (this.getCitizenship() == null ? other.getCitizenship() == null : this.getCitizenship().equals(other.getCitizenship()))
                && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
                && (this.getBirthDay() == null ? other.getBirthDay() == null : this.getBirthDay().equals(other.getBirthDay()))
                && (this.getPolitics() == null ? other.getPolitics() == null : this.getPolitics().equals(other.getPolitics()))
                && (this.getIdcardType() == null ? other.getIdcardType() == null : this.getIdcardType().equals(other.getIdcardType()))
                && (this.getIdcardNumber() == null ? other.getIdcardNumber() == null : this.getIdcardNumber().equals(other.getIdcardNumber()))
                && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
                && (this.getDegree() == null ? other.getDegree() == null : this.getDegree().equals(other.getDegree()))
                && (this.getMajorName() == null ? other.getMajorName() == null : this.getMajorName().equals(other.getMajorName()))
                && (this.getStature() == null ? other.getStature() == null : this.getStature().equals(other.getStature()))
                && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
                && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
                && (this.getNativePlace() == null ? other.getNativePlace() == null : this.getNativePlace().equals(other.getNativePlace()))
                && (this.getNationality() == null ? other.getNationality() == null : this.getNationality().equals(other.getNationality()))
                && (this.getJobNumber() == null ? other.getJobNumber() == null : this.getJobNumber().equals(other.getJobNumber()))
                && (this.getMarriageState() == null ? other.getMarriageState() == null : this.getMarriageState().equals(other.getMarriageState()))
                && (this.getEmergencyPhone() == null ? other.getEmergencyPhone() == null : this.getEmergencyPhone().equals(other.getEmergencyPhone()))
                && (this.getEmergencyName() == null ? other.getEmergencyName() == null : this.getEmergencyName().equals(other.getEmergencyName()))
                && (this.getOfficeLocation() == null ? other.getOfficeLocation() == null : this.getOfficeLocation().equals(other.getOfficeLocation()))
                && (this.getSignToken() == null ? other.getSignToken() == null : this.getSignToken().equals(other.getSignToken()))
                && (this.getPhotoToken() == null ? other.getPhotoToken() == null : this.getPhotoToken().equals(other.getPhotoToken()))
                && (this.getIsInitPwd() == null ? other.getIsInitPwd() == null : this.getIsInitPwd().equals(other.getIsInitPwd()))
                && (this.getOfficePhone() == null ? other.getOfficePhone() == null : this.getOfficePhone().equals(other.getOfficePhone()))
                && (this.getOtherPhone() == null ? other.getOtherPhone() == null : this.getOtherPhone().equals(other.getOtherPhone()))
                && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
                && (this.getWorkingSeniority() == null ? other.getWorkingSeniority() == null : this.getWorkingSeniority().equals(other.getWorkingSeniority()))
                && (this.getHiredate() == null ? other.getHiredate() == null : this.getHiredate().equals(other.getHiredate()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getLastUpdatePwdTime() == null ? other.getLastUpdatePwdTime() == null : this.getLastUpdatePwdTime().equals(other.getLastUpdatePwdTime()))
                && (this.getAvatarToken() == null ? other.getAvatarToken() == null : this.getAvatarToken().equals(other.getAvatarToken()))
                && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
                && (this.getIntroduction() == null ? other.getIntroduction() == null : this.getIntroduction().equals(other.getIntroduction()))
                && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
                && (this.getExt1() == null ? other.getExt1() == null : this.getExt1().equals(other.getExt1()))
                && (this.getExt2() == null ? other.getExt2() == null : this.getExt2().equals(other.getExt2()))
                && (this.getExt3() == null ? other.getExt3() == null : this.getExt3().equals(other.getExt3()))
                && (this.getExt4() == null ? other.getExt4() == null : this.getExt4().equals(other.getExt4()))
                && (this.getExt5() == null ? other.getExt5() == null : this.getExt5().equals(other.getExt5()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserNo() == null) ? 0 : getUserNo().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getUserFullname() == null) ? 0 : getUserFullname().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getAccountStatus() == null) ? 0 : getAccountStatus().hashCode());
        result = prime * result + ((getAccountPeriod() == null) ? 0 : getAccountPeriod().hashCode());
        result = prime * result + ((getLastActiveTime() == null) ? 0 : getLastActiveTime().hashCode());
        result = prime * result + ((getFormerName() == null) ? 0 : getFormerName().hashCode());
        result = prime * result + ((getCitizenship() == null) ? 0 : getCitizenship().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getBirthDay() == null) ? 0 : getBirthDay().hashCode());
        result = prime * result + ((getPolitics() == null) ? 0 : getPolitics().hashCode());
        result = prime * result + ((getIdcardType() == null) ? 0 : getIdcardType().hashCode());
        result = prime * result + ((getIdcardNumber() == null) ? 0 : getIdcardNumber().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getDegree() == null) ? 0 : getDegree().hashCode());
        result = prime * result + ((getMajorName() == null) ? 0 : getMajorName().hashCode());
        result = prime * result + ((getStature() == null) ? 0 : getStature().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getNativePlace() == null) ? 0 : getNativePlace().hashCode());
        result = prime * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
        result = prime * result + ((getJobNumber() == null) ? 0 : getJobNumber().hashCode());
        result = prime * result + ((getMarriageState() == null) ? 0 : getMarriageState().hashCode());
        result = prime * result + ((getEmergencyPhone() == null) ? 0 : getEmergencyPhone().hashCode());
        result = prime * result + ((getEmergencyName() == null) ? 0 : getEmergencyName().hashCode());
        result = prime * result + ((getOfficeLocation() == null) ? 0 : getOfficeLocation().hashCode());
        result = prime * result + ((getSignToken() == null) ? 0 : getSignToken().hashCode());
        result = prime * result + ((getPhotoToken() == null) ? 0 : getPhotoToken().hashCode());
        result = prime * result + ((getIsInitPwd() == null) ? 0 : getIsInitPwd().hashCode());
        result = prime * result + ((getOfficePhone() == null) ? 0 : getOfficePhone().hashCode());
        result = prime * result + ((getOtherPhone() == null) ? 0 : getOtherPhone().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getWorkingSeniority() == null) ? 0 : getWorkingSeniority().hashCode());
        result = prime * result + ((getHiredate() == null) ? 0 : getHiredate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getLastUpdatePwdTime() == null) ? 0 : getLastUpdatePwdTime().hashCode());
        result = prime * result + ((getAvatarToken() == null) ? 0 : getAvatarToken().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getExt1() == null) ? 0 : getExt1().hashCode());
        result = prime * result + ((getExt2() == null) ? 0 : getExt2().hashCode());
        result = prime * result + ((getExt3() == null) ? 0 : getExt3().hashCode());
        result = prime * result + ((getExt4() == null) ? 0 : getExt4().hashCode());
        result = prime * result + ((getExt5() == null) ? 0 : getExt5().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", userNo=").append(userNo);
        sb.append(", password=").append(password);
        sb.append(", userFullname=").append(userFullname);
        sb.append(", sex=").append(sex);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", userType=").append(userType);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", accountStatus=").append(accountStatus);
        sb.append(", accountPeriod=").append(accountPeriod);
        sb.append(", lastActiveTime=").append(lastActiveTime);
        sb.append(", formerName=").append(formerName);
        sb.append(", citizenship=").append(citizenship);
        sb.append(", age=").append(age);
        sb.append(", birthDay=").append(birthDay);
        sb.append(", politics=").append(politics);
        sb.append(", idcardType=").append(idcardType);
        sb.append(", idcardNumber=").append(idcardNumber);
        sb.append(", education=").append(education);
        sb.append(", degree=").append(degree);
        sb.append(", majorName=").append(majorName);
        sb.append(", stature=").append(stature);
        sb.append(", weight=").append(weight);
        sb.append(", nation=").append(nation);
        sb.append(", nativePlace=").append(nativePlace);
        sb.append(", nationality=").append(nationality);
        sb.append(", jobNumber=").append(jobNumber);
        sb.append(", marriageState=").append(marriageState);
        sb.append(", emergencyPhone=").append(emergencyPhone);
        sb.append(", emergencyName=").append(emergencyName);
        sb.append(", officeLocation=").append(officeLocation);
        sb.append(", signToken=").append(signToken);
        sb.append(", photoToken=").append(photoToken);
        sb.append(", isInitPwd=").append(isInitPwd);
        sb.append(", officePhone=").append(officePhone);
        sb.append(", otherPhone=").append(otherPhone);
        sb.append(", title=").append(title);
        sb.append(", workingSeniority=").append(workingSeniority);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", remark=").append(remark);
        sb.append(", lastUpdatePwdTime=").append(lastUpdatePwdTime);
        sb.append(", avatarToken=").append(avatarToken);
        sb.append(", nickname=").append(nickname);
        sb.append(", introduction=").append(introduction);
        sb.append(", sort=").append(sort);
        sb.append(", ext1=").append(ext1);
        sb.append(", ext2=").append(ext2);
        sb.append(", ext3=").append(ext3);
        sb.append(", ext4=").append(ext4);
        sb.append(", ext5=").append(ext5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}