package com.fawkes.sys.storage.common.model;

import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;

public class SysOssLicense extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.active
     *
     * @mbggenerated
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.file_token
     *
     * @mbggenerated
     */
    private String fileToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss_license.endpoint_key
     *
     * @mbggenerated
     */
    private String endpointKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_oss_license
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.id
     *
     * @return the value of sys_oss_license.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.id
     *
     * @param id the value for sys_oss_license.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.active
     *
     * @return the value of sys_oss_license.active
     *
     * @mbggenerated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.active
     *
     * @param active the value for sys_oss_license.active
     *
     * @mbggenerated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.file_token
     *
     * @return the value of sys_oss_license.file_token
     *
     * @mbggenerated
     */
    public String getFileToken() {
        return fileToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.file_token
     *
     * @param fileToken the value for sys_oss_license.file_token
     *
     * @mbggenerated
     */
    public void setFileToken(String fileToken) {
        this.fileToken = fileToken == null ? null : fileToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.object_name
     *
     * @return the value of sys_oss_license.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.object_name
     *
     * @param objectName the value for sys_oss_license.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.client_id
     *
     * @return the value of sys_oss_license.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.client_id
     *
     * @param clientId the value for sys_oss_license.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss_license.endpoint_key
     *
     * @return the value of sys_oss_license.endpoint_key
     *
     * @mbggenerated
     */
    public String getEndpointKey() {
        return endpointKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss_license.endpoint_key
     *
     * @param endpointKey the value for sys_oss_license.endpoint_key
     *
     * @mbggenerated
     */
    public void setEndpointKey(String endpointKey) {
        this.endpointKey = endpointKey == null ? null : endpointKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss_license
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOssLicense other = (SysOssLicense) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getFileToken() == null ? other.getFileToken() == null : this.getFileToken().equals(other.getFileToken()))
            && (this.getObjectName() == null ? other.getObjectName() == null : this.getObjectName().equals(other.getObjectName()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getEndpointKey() == null ? other.getEndpointKey() == null : this.getEndpointKey().equals(other.getEndpointKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss_license
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getFileToken() == null) ? 0 : getFileToken().hashCode());
        result = prime * result + ((getObjectName() == null) ? 0 : getObjectName().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getEndpointKey() == null) ? 0 : getEndpointKey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss_license
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", active=").append(active);
        sb.append(", fileToken=").append(fileToken);
        sb.append(", objectName=").append(objectName);
        sb.append(", clientId=").append(clientId);
        sb.append(", endpointKey=").append(endpointKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}