package com.fawkes.sys.storage.common.model;

import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;

public class SysOss extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.file_token
     *
     * @mbggenerated
     */
    private String fileToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.bucket_name
     *
     * @mbggenerated
     */
    private String bucketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.ext_name
     *
     * @mbggenerated
     */
    private String extName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.endpoint_key
     *
     * @mbggenerated
     */
    private String endpointKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.group_token
     *
     * @mbggenerated
     */
    private String groupToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.object_name
     *
     * @mbggenerated
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oss.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_oss
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.file_token
     *
     * @return the value of sys_oss.file_token
     *
     * @mbggenerated
     */
    public String getFileToken() {
        return fileToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.file_token
     *
     * @param fileToken the value for sys_oss.file_token
     *
     * @mbggenerated
     */
    public void setFileToken(String fileToken) {
        this.fileToken = fileToken == null ? null : fileToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.file_name
     *
     * @return the value of sys_oss.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.file_name
     *
     * @param fileName the value for sys_oss.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.bucket_name
     *
     * @return the value of sys_oss.bucket_name
     *
     * @mbggenerated
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.bucket_name
     *
     * @param bucketName the value for sys_oss.bucket_name
     *
     * @mbggenerated
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.ext_name
     *
     * @return the value of sys_oss.ext_name
     *
     * @mbggenerated
     */
    public String getExtName() {
        return extName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.ext_name
     *
     * @param extName the value for sys_oss.ext_name
     *
     * @mbggenerated
     */
    public void setExtName(String extName) {
        this.extName = extName == null ? null : extName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.endpoint_key
     *
     * @return the value of sys_oss.endpoint_key
     *
     * @mbggenerated
     */
    public String getEndpointKey() {
        return endpointKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.endpoint_key
     *
     * @param endpointKey the value for sys_oss.endpoint_key
     *
     * @mbggenerated
     */
    public void setEndpointKey(String endpointKey) {
        this.endpointKey = endpointKey == null ? null : endpointKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.group_token
     *
     * @return the value of sys_oss.group_token
     *
     * @mbggenerated
     */
    public String getGroupToken() {
        return groupToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.group_token
     *
     * @param groupToken the value for sys_oss.group_token
     *
     * @mbggenerated
     */
    public void setGroupToken(String groupToken) {
        this.groupToken = groupToken == null ? null : groupToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.dir
     *
     * @return the value of sys_oss.dir
     *
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.dir
     *
     * @param dir the value for sys_oss.dir
     *
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.size
     *
     * @return the value of sys_oss.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.size
     *
     * @param size the value for sys_oss.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.version
     *
     * @return the value of sys_oss.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.version
     *
     * @param version the value for sys_oss.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.object_name
     *
     * @return the value of sys_oss.object_name
     *
     * @mbggenerated
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.object_name
     *
     * @param objectName the value for sys_oss.object_name
     *
     * @mbggenerated
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.tag
     *
     * @return the value of sys_oss.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.tag
     *
     * @param tag the value for sys_oss.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oss.md5
     *
     * @return the value of sys_oss.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oss.md5
     *
     * @param md5 the value for sys_oss.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOss other = (SysOss) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getFileToken() == null ? other.getFileToken() == null : this.getFileToken().equals(other.getFileToken()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getBucketName() == null ? other.getBucketName() == null : this.getBucketName().equals(other.getBucketName()))
            && (this.getExtName() == null ? other.getExtName() == null : this.getExtName().equals(other.getExtName()))
            && (this.getEndpointKey() == null ? other.getEndpointKey() == null : this.getEndpointKey().equals(other.getEndpointKey()))
            && (this.getGroupToken() == null ? other.getGroupToken() == null : this.getGroupToken().equals(other.getGroupToken()))
            && (this.getDir() == null ? other.getDir() == null : this.getDir().equals(other.getDir()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getObjectName() == null ? other.getObjectName() == null : this.getObjectName().equals(other.getObjectName()))
            && (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
            && (this.getMd5() == null ? other.getMd5() == null : this.getMd5().equals(other.getMd5()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getFileToken() == null) ? 0 : getFileToken().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getBucketName() == null) ? 0 : getBucketName().hashCode());
        result = prime * result + ((getExtName() == null) ? 0 : getExtName().hashCode());
        result = prime * result + ((getEndpointKey() == null) ? 0 : getEndpointKey().hashCode());
        result = prime * result + ((getGroupToken() == null) ? 0 : getGroupToken().hashCode());
        result = prime * result + ((getDir() == null) ? 0 : getDir().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getObjectName() == null) ? 0 : getObjectName().hashCode());
        result = prime * result + ((getTag() == null) ? 0 : getTag().hashCode());
        result = prime * result + ((getMd5() == null) ? 0 : getMd5().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oss
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileToken=").append(fileToken);
        sb.append(", fileName=").append(fileName);
        sb.append(", bucketName=").append(bucketName);
        sb.append(", extName=").append(extName);
        sb.append(", endpointKey=").append(endpointKey);
        sb.append(", groupToken=").append(groupToken);
        sb.append(", dir=").append(dir);
        sb.append(", size=").append(size);
        sb.append(", version=").append(version);
        sb.append(", objectName=").append(objectName);
        sb.append(", tag=").append(tag);
        sb.append(", md5=").append(md5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}