package com.fawkes.sys.msg.common.model.fawkes;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.fawkes.core.base.model.BaseEntity;
import java.io.Serializable;

public class SysMsg extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_type
     *
     * @mbggenerated
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_send_status
     *
     * @mbggenerated
     */
    private Integer msgSendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_send_type
     *
     * @mbggenerated
     */
    private Integer msgSendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.from_client_id
     *
     * @mbggenerated
     */
    private String fromClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.from_user_id
     *
     * @mbggenerated
     */
    @JsonSerialize(
            using = ToStringSerializer.class
    )
    private Long fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.from_tenant_id
     *
     * @mbggenerated
     */
    private Integer fromTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.from_user_name
     *
     * @mbggenerated
     */
    private String fromUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.from_user_fullname
     *
     * @mbggenerated
     */
    private String fromUserFullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.to_client_id
     *
     * @mbggenerated
     */
    private String toClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_template_id
     *
     * @mbggenerated
     */
    @JsonSerialize(
            using = ToStringSerializer.class
    )
    private Long msgTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_type
     *
     * @return the value of sys_msg.msg_type
     *
     * @mbggenerated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_type
     *
     * @param msgType the value for sys_msg.msg_type
     *
     * @mbggenerated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_send_status
     *
     * @return the value of sys_msg.msg_send_status
     *
     * @mbggenerated
     */
    public Integer getMsgSendStatus() {
        return msgSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_send_status
     *
     * @param msgSendStatus the value for sys_msg.msg_send_status
     *
     * @mbggenerated
     */
    public void setMsgSendStatus(Integer msgSendStatus) {
        this.msgSendStatus = msgSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_send_type
     *
     * @return the value of sys_msg.msg_send_type
     *
     * @mbggenerated
     */
    public Integer getMsgSendType() {
        return msgSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_send_type
     *
     * @param msgSendType the value for sys_msg.msg_send_type
     *
     * @mbggenerated
     */
    public void setMsgSendType(Integer msgSendType) {
        this.msgSendType = msgSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.from_client_id
     *
     * @return the value of sys_msg.from_client_id
     *
     * @mbggenerated
     */
    public String getFromClientId() {
        return fromClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.from_client_id
     *
     * @param fromClientId the value for sys_msg.from_client_id
     *
     * @mbggenerated
     */
    public void setFromClientId(String fromClientId) {
        this.fromClientId = fromClientId == null ? null : fromClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.from_user_id
     *
     * @return the value of sys_msg.from_user_id
     *
     * @mbggenerated
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.from_user_id
     *
     * @param fromUserId the value for sys_msg.from_user_id
     *
     * @mbggenerated
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.from_tenant_id
     *
     * @return the value of sys_msg.from_tenant_id
     *
     * @mbggenerated
     */
    public Integer getFromTenantId() {
        return fromTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.from_tenant_id
     *
     * @param fromTenantId the value for sys_msg.from_tenant_id
     *
     * @mbggenerated
     */
    public void setFromTenantId(Integer fromTenantId) {
        this.fromTenantId = fromTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.from_user_name
     *
     * @return the value of sys_msg.from_user_name
     *
     * @mbggenerated
     */
    public String getFromUserName() {
        return fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.from_user_name
     *
     * @param fromUserName the value for sys_msg.from_user_name
     *
     * @mbggenerated
     */
    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName == null ? null : fromUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.from_user_fullname
     *
     * @return the value of sys_msg.from_user_fullname
     *
     * @mbggenerated
     */
    public String getFromUserFullname() {
        return fromUserFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.from_user_fullname
     *
     * @param fromUserFullname the value for sys_msg.from_user_fullname
     *
     * @mbggenerated
     */
    public void setFromUserFullname(String fromUserFullname) {
        this.fromUserFullname = fromUserFullname == null ? null : fromUserFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.to_client_id
     *
     * @return the value of sys_msg.to_client_id
     *
     * @mbggenerated
     */
    public String getToClientId() {
        return toClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.to_client_id
     *
     * @param toClientId the value for sys_msg.to_client_id
     *
     * @mbggenerated
     */
    public void setToClientId(String toClientId) {
        this.toClientId = toClientId == null ? null : toClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_template_id
     *
     * @return the value of sys_msg.msg_template_id
     *
     * @mbggenerated
     */
    public Long getMsgTemplateId() {
        return msgTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_template_id
     *
     * @param msgTemplateId the value for sys_msg.msg_template_id
     *
     * @mbggenerated
     */
    public void setMsgTemplateId(Long msgTemplateId) {
        this.msgTemplateId = msgTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMsg other = (SysMsg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getMsgSendStatus() == null ? other.getMsgSendStatus() == null : this.getMsgSendStatus().equals(other.getMsgSendStatus()))
            && (this.getMsgSendType() == null ? other.getMsgSendType() == null : this.getMsgSendType().equals(other.getMsgSendType()))
            && (this.getFromClientId() == null ? other.getFromClientId() == null : this.getFromClientId().equals(other.getFromClientId()))
            && (this.getFromUserId() == null ? other.getFromUserId() == null : this.getFromUserId().equals(other.getFromUserId()))
            && (this.getFromTenantId() == null ? other.getFromTenantId() == null : this.getFromTenantId().equals(other.getFromTenantId()))
            && (this.getFromUserName() == null ? other.getFromUserName() == null : this.getFromUserName().equals(other.getFromUserName()))
            && (this.getFromUserFullname() == null ? other.getFromUserFullname() == null : this.getFromUserFullname().equals(other.getFromUserFullname()))
            && (this.getToClientId() == null ? other.getToClientId() == null : this.getToClientId().equals(other.getToClientId()))
            && (this.getMsgTemplateId() == null ? other.getMsgTemplateId() == null : this.getMsgTemplateId().equals(other.getMsgTemplateId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getMsgSendStatus() == null) ? 0 : getMsgSendStatus().hashCode());
        result = prime * result + ((getMsgSendType() == null) ? 0 : getMsgSendType().hashCode());
        result = prime * result + ((getFromClientId() == null) ? 0 : getFromClientId().hashCode());
        result = prime * result + ((getFromUserId() == null) ? 0 : getFromUserId().hashCode());
        result = prime * result + ((getFromTenantId() == null) ? 0 : getFromTenantId().hashCode());
        result = prime * result + ((getFromUserName() == null) ? 0 : getFromUserName().hashCode());
        result = prime * result + ((getFromUserFullname() == null) ? 0 : getFromUserFullname().hashCode());
        result = prime * result + ((getToClientId() == null) ? 0 : getToClientId().hashCode());
        result = prime * result + ((getMsgTemplateId() == null) ? 0 : getMsgTemplateId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgType=").append(msgType);
        sb.append(", msgSendStatus=").append(msgSendStatus);
        sb.append(", msgSendType=").append(msgSendType);
        sb.append(", fromClientId=").append(fromClientId);
        sb.append(", fromUserId=").append(fromUserId);
        sb.append(", fromTenantId=").append(fromTenantId);
        sb.append(", fromUserName=").append(fromUserName);
        sb.append(", fromUserFullname=").append(fromUserFullname);
        sb.append(", toClientId=").append(toClientId);
        sb.append(", msgTemplateId=").append(msgTemplateId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}