package com.fawkes.sys.msg.common.model.fawkes;

import java.io.Serializable;

public class SysMsgWithBLOBs extends SysMsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_template_param
     *
     * @mbggenerated
     */
    private String msgTemplateParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.to_users
     *
     * @mbggenerated
     */
    private String toUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg.msg_body
     *
     * @mbggenerated
     */
    private String msgBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_template_param
     *
     * @return the value of sys_msg.msg_template_param
     *
     * @mbggenerated
     */
    public String getMsgTemplateParam() {
        return msgTemplateParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_template_param
     *
     * @param msgTemplateParam the value for sys_msg.msg_template_param
     *
     * @mbggenerated
     */
    public void setMsgTemplateParam(String msgTemplateParam) {
        this.msgTemplateParam = msgTemplateParam == null ? null : msgTemplateParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.to_users
     *
     * @return the value of sys_msg.to_users
     *
     * @mbggenerated
     */
    public String getToUsers() {
        return toUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.to_users
     *
     * @param toUsers the value for sys_msg.to_users
     *
     * @mbggenerated
     */
    public void setToUsers(String toUsers) {
        this.toUsers = toUsers == null ? null : toUsers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg.msg_body
     *
     * @return the value of sys_msg.msg_body
     *
     * @mbggenerated
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg.msg_body
     *
     * @param msgBody the value for sys_msg.msg_body
     *
     * @mbggenerated
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody == null ? null : msgBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMsgWithBLOBs other = (SysMsgWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getMsgSendStatus() == null ? other.getMsgSendStatus() == null : this.getMsgSendStatus().equals(other.getMsgSendStatus()))
            && (this.getMsgSendType() == null ? other.getMsgSendType() == null : this.getMsgSendType().equals(other.getMsgSendType()))
            && (this.getFromClientId() == null ? other.getFromClientId() == null : this.getFromClientId().equals(other.getFromClientId()))
            && (this.getFromUserId() == null ? other.getFromUserId() == null : this.getFromUserId().equals(other.getFromUserId()))
            && (this.getFromTenantId() == null ? other.getFromTenantId() == null : this.getFromTenantId().equals(other.getFromTenantId()))
            && (this.getFromUserName() == null ? other.getFromUserName() == null : this.getFromUserName().equals(other.getFromUserName()))
            && (this.getFromUserFullname() == null ? other.getFromUserFullname() == null : this.getFromUserFullname().equals(other.getFromUserFullname()))
            && (this.getToClientId() == null ? other.getToClientId() == null : this.getToClientId().equals(other.getToClientId()))
            && (this.getMsgTemplateId() == null ? other.getMsgTemplateId() == null : this.getMsgTemplateId().equals(other.getMsgTemplateId()))
            && (this.getMsgTemplateParam() == null ? other.getMsgTemplateParam() == null : this.getMsgTemplateParam().equals(other.getMsgTemplateParam()))
            && (this.getToUsers() == null ? other.getToUsers() == null : this.getToUsers().equals(other.getToUsers()))
            && (this.getMsgBody() == null ? other.getMsgBody() == null : this.getMsgBody().equals(other.getMsgBody()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getMsgSendStatus() == null) ? 0 : getMsgSendStatus().hashCode());
        result = prime * result + ((getMsgSendType() == null) ? 0 : getMsgSendType().hashCode());
        result = prime * result + ((getFromClientId() == null) ? 0 : getFromClientId().hashCode());
        result = prime * result + ((getFromUserId() == null) ? 0 : getFromUserId().hashCode());
        result = prime * result + ((getFromTenantId() == null) ? 0 : getFromTenantId().hashCode());
        result = prime * result + ((getFromUserName() == null) ? 0 : getFromUserName().hashCode());
        result = prime * result + ((getFromUserFullname() == null) ? 0 : getFromUserFullname().hashCode());
        result = prime * result + ((getToClientId() == null) ? 0 : getToClientId().hashCode());
        result = prime * result + ((getMsgTemplateId() == null) ? 0 : getMsgTemplateId().hashCode());
        result = prime * result + ((getMsgTemplateParam() == null) ? 0 : getMsgTemplateParam().hashCode());
        result = prime * result + ((getToUsers() == null) ? 0 : getToUsers().hashCode());
        result = prime * result + ((getMsgBody() == null) ? 0 : getMsgBody().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgTemplateParam=").append(msgTemplateParam);
        sb.append(", toUsers=").append(toUsers);
        sb.append(", msgBody=").append(msgBody);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}