package com.fawkes.sys.msg.common.model.fawkes;

import java.io.Serializable;

public class SysMsgTemplateGroupWithBLOBs extends SysMsgTemplateGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg_template_group.param_list
     *
     * @mbggenerated
     */
    private String paramList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_msg_template_group.mapping_rule
     *
     * @mbggenerated
     */
    private String mappingRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_msg_template_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg_template_group.param_list
     *
     * @return the value of sys_msg_template_group.param_list
     *
     * @mbggenerated
     */
    public String getParamList() {
        return paramList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg_template_group.param_list
     *
     * @param paramList the value for sys_msg_template_group.param_list
     *
     * @mbggenerated
     */
    public void setParamList(String paramList) {
        this.paramList = paramList == null ? null : paramList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_msg_template_group.mapping_rule
     *
     * @return the value of sys_msg_template_group.mapping_rule
     *
     * @mbggenerated
     */
    public String getMappingRule() {
        return mappingRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_msg_template_group.mapping_rule
     *
     * @param mappingRule the value for sys_msg_template_group.mapping_rule
     *
     * @mbggenerated
     */
    public void setMappingRule(String mappingRule) {
        this.mappingRule = mappingRule == null ? null : mappingRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg_template_group
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMsgTemplateGroupWithBLOBs other = (SysMsgTemplateGroupWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getGroupName() == null ? other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
            && (this.getParamList() == null ? other.getParamList() == null : this.getParamList().equals(other.getParamList()))
            && (this.getMappingRule() == null ? other.getMappingRule() == null : this.getMappingRule().equals(other.getMappingRule()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg_template_group
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getParamList() == null) ? 0 : getParamList().hashCode());
        result = prime * result + ((getMappingRule() == null) ? 0 : getMappingRule().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg_template_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paramList=").append(paramList);
        sb.append(", mappingRule=").append(mappingRule);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}